# 1. DB의 고정 주소를 만들어주는 Service
apiVersion: v1
kind: Service
metadata:
  name: sk007-project-db
  namespace: skala3-ai1
spec:
  selector:
    app: project-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
# 2. 실제 DB 컨테이너를 띄우는 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk007-project-db-deployment
  namespace: skala3-ai1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-db
  template:
    metadata:
      labels:
        app: project-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.4
        ports:
        - containerPort: 3306
        env:
        - name: TZ
          value: Asia/Seoul
        - name: MARIADB_ROOT_PASSWORD
          value: mysql_1
        - name: MARIADB_DATABASE
          value: smart_glass_dev
        - name: MARIADB_USER
          value: sg_app
        - name: MARIADB_PASSWORD
          value: sg_app_1
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --lower_case_table_names=1

        # volumeMounts에 PVC 연결 추가
        volumeMounts:
        - name: db-storage       # PVC 외장 하드 연결
          mountPath: /var/lib/mysql
        - name: initdb-volume    # DB 초기화 스크립트 연결
          mountPath: /docker-entrypoint-initdb.d
          
      # volumes에 PVC 연결 추가
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: sk007-db-pvc
      - name: initdb-volume
        configMap:
          name: mariadb-initdb-config