# 기존 v1 서비스로 90% 라우팅되는 Main Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk007-ingress
  namespace: skala3-ai1
  annotations:
    # 외부에서 /sk007-ai/주소 로 들어오면, 
    # 앞의 /sk007-ai를 자르고 주소만 서비스로 넘겨주는 설정 (rewrite)
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # 정규식 사용 허용 (rewrite-target에서 $2 쓰기 위해 nginx에게 허락 받기)
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: public-nginx
  rules:
  - host: sk007-smart-glass.project.skala-ai.com
    http:
      paths:
      # AI 서버로 가는 라우팅 규칙
      - path: /sk007-ai(/|$)(.*)
        pathType: ImplementationSpecific # ★ Prefix 대신 사용
        backend:
          service:
            name: sk007-ai-server-service-v1
            port:
              # Service에서 열어둔 포트 번호
              number: 80 
              
      # Auth 서버(Spring Boot)로 가는 라우팅 규칙
      - path: /sk007-auth(/|$)(.*)
        pathType: ImplementationSpecific # ★ Prefix 대신 사용
        backend:
          service:
            name: sk007-auth-server-service
            port:
              number: 80

---
# 신규 v2 서비스로 10% 라우팅되는 Canary Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk007-ai-ingress-canary
  namespace: skala3-ai1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # 카나리 배포 설정 및 가중치(10%) 지정
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: public-nginx
  rules:
  - host: sk007-smart-glass.project.skala-ai.com
    http:
      paths:
      # 호스트와 경로는 Main Ingress와 완전히 동일해야 함
      - path: /sk007-ai(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sk007-ai-server-service-v2
            port:
              number: 80
