name: smart-glass-cd-pipeline

on:
  push:
    branches:
      - main
    # k8s 폴더 안에 변경 사항이 있을 때만 배포 파이프라인 실행
    paths:
      - 'k8s/**'

jobs:
  deploy-to-eks:
    name: Deploy to EKS
    needs: [build-auth-server, build-ai-server] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      # AWS 키가 GitHub Secrets에 있어야 작동
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # EKS skala-2025 출입증 발급
      - name: Update KubeConfig
        run: aws eks update-kubeconfig --name skala-2025 --region ap-northeast-2

      # k8s 폴더 안 모든 yaml 파일을 쿠버네티스에 적용
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/